package:
  name: keycloak-darkfellanet
  version: "26.6.1"
  epoch: 0
  description: Open Source Identity and Access Management For Modern Applications and Services
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash # Keycloak helper scripts require bash, aren't compatible with busybox.
      - merged-usrsbin
      - openjdk-${{vars.java-version}}-default-jvm
      - wolfi-baselayout
vars:
  java-version: 21
environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - gcc-13-default
      - nodejs
      - openjdk-${{vars.java-version}}-default-jdk
      - pnpm
      - npm
      - unzip
      - wolfi-base
      - wolfi-baselayout
      - maven
      - node-gyp
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-${{vars.java-version}}-openjdk
    REPRODUCIBLE: false
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/keycloak/keycloak
      tag: ${{package.version}}
      expected-commit: 5bebfac09dd9abc5fe8b43f00ac596f0a5c998d1
  - runs: |
      gcc napi-static-assert.c -o /tmp/preload.so -fPIC -shared -ldl
  - runs: |
      export LD_PRELOAD=/tmp/preload.so
      ./mvnw clean install -DskipTests -Dmaven.test.skip=true -DskipITs -DskipProtoLock=true -Pdistribution
      unset LD_PRELOAD

      mkdir -p ${{targets.destdir}}/usr/share/java
      unzip -d ${{targets.destdir}}/usr/share/java quarkus/dist/target/keycloak-*.zip
      mv ${{targets.destdir}}/usr/share/java/keycloak-* ${{targets.destdir}}/usr/share/java/keycloak

      mkdir -p ${{targets.destdir}}/usr/share/java/keycloak/data

      mkdir -p ${{targets.destdir}}/usr/bin
      for i in kc.sh kcadm.sh kcreg.sh; do
        ln -sf /usr/share/java/keycloak/bin/$i ${{targets.destdir}}/usr/bin/$i
      done
  - uses: git-checkout
    with:
      repository: https://github.com/d4rkfella/keycloak-custom-theme
      tag: v0.2.3
      expected-commit: 877e4a7557e505425b21d8a7c6bc91fe24abd15d
  - runs: |
      npm install
      npm run build-keycloak-theme
      cp dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar ${{targets.destdir}}/usr/share/java/keycloak/providers/keycloak-theme.jar
  - runs: |
      export KC_HEALTH_ENABLED=true
      export KC_METRICS_ENABLED=true
      export KC_DB=postgres
      cd "${{targets.destdir}}"/usr/share/java/keycloak && "${{targets.destdir}}"/usr/share/java/keycloak/bin/kc.sh build
subpackages:
  - name: ${{package.name}}-operator
    dependencies:
      runtime:
        - openjdk-${{vars.java-version}}-default-jdk
    pipeline:
      - name: "build and install files"
        runs: |
          cd operator
          ../mvnw clean package

          destdir="${{targets.subpkgdir}}/usr/share/java"
          mkdir -p "$destdir"
          maven_name="keycloak-operator-${{package.version}}"
          unzip "target/${maven_name}.zip" -d "$destdir"
          mv "${destdir}/${maven_name}" "${destdir}/quarkus-app"

          ls -lr "$destdir"
    test:
      pipeline:
        - name: "expected initialization error test"
          runs: |
            set +e
            output=$(java -Djava.util.logging.manager=org.jboss.logmanager.LogManager \
              -jar /usr/share/java/quarkus-app/quarkus-run.jar 2>&1)
            set -e
            echo "$output" | grep -q "Couldn't retrieve the currently connected namespace"
  - name: ${{package.name}}-operator-compat
    pipeline:
      - name: "install files"
        runs: |
          mkdir -p "${{targets.subpkgdir}}"/opt/
          ln -s /usr/share/java/quarkus-app/ "${{targets.subpkgdir}}"/opt/keycloak
    test:
      pipeline:
        - name: "verify expected link exists"
          runs: readlink /opt/keycloak
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/opt
          ln -s /usr/share/java/keycloak "${{targets.subpkgdir}}"/opt/
    dependencies:
      runtime:
        - merged-usrsbin
        - wolfi-baselayout
test:
  pipeline:
    - name: "start daemon on localhost"
      uses: test/daemon-check-output
      with:
        start: "kc.sh start --hostname=localhost --https-key-store-password=MYPASSWORD"
        timeout: 60
        expected_output: |
          Listening on
          Keycloak ${{package.version}}
          Profile prod activated
        setup: |
          #!/bin/sh -ex
          echo "127.0.0.1 $(hostname)" >> /etc/hosts
          kspath=/usr/share/java/keycloak/conf/server.keystore
          keytool -v \
              -keystore $kspath \
              -alias localhost \
              -genkeypair -sigalg SHA512withRSA -keyalg RSA -dname CN=localhost \
              -storepass MYPASSWORD || {
                echo "failed [$?] to create keystore with keytool at $kspath"
                exit 1
          }
    - name: "version and help tests"
      runs: |
        kc.sh --version
        kc.sh --help
        kcadm.sh --help
        kcreg.sh --help
update:
  ignore-regex-patterns:
    - ".*nightly.*"
  enabled: true
  github:
    identifier: keycloak/keycloak
