package:
  name: qbittorrent
  version: "5.2.0.2012"
  epoch: 0
  description: The qbittorrent-nox-static project is a bash build script that compiles a static qbittorrent-nox binary using the latest available dependencies from their source.
  copyright:
    - license: Apache-2.0
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
      - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
    packages:
      - alpine-baselayout-data
      - alpine-release
      - ca-certificates-bundle
      - apk-tools
      - bash
  environment:
    REPRODUCIBLE: false
var-transforms:
  - from: ${{package.version}}
    match: \.(\d)(\d)(\d+)$
    replace: _v$1.$2.$3
    to: mangled-package-version
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/userdocs/qbittorrent-nox-static
      tag: release-${{vars.mangled-package-version}}
      expected-commit: bd11018bb8753141a6ff9198759e306195216e8c
  - runs: |
      printf '%s\n' "qbt_build_dir=qbt-build" > env.custom
      printf '%s\n' "qbt_libtorrent_version=2.0" >> env.custom
      printf '%s\n' "qbt_qt_version=6" >> env.custom
      printf '%s\n' "qbt_build_tool=" >> env.custom
      printf '%s\n' "qbt_cross_name=${{build.arch}}" >> env.custom
      printf '%s\n' "qbt_patches_url=userdocs/qbittorrent-nox-static" >> env.custom
      printf '%s\n' "qbt_skip_icu=yes" >> env.custom
      printf '%s\n' "qbt_boost_tag=" >> env.custom
      printf '%s\n' "qbt_libtorrent_tag=" >> env.custom
      printf '%s\n' "qbt_qt_tag=" >> env.custom
      printf '%s\n' "qbt_qbittorrent_tag=" >> env.custom
      printf '%s\n' "qbt_libtorrent_master_jamfile=" >> env.custom
      printf '%s\n' "qbt_workflow_files=" >> env.custom
      printf '%s\n' "qbt_workflow_artifacts=" >> env.custom
      printf '%s\n' "qbt_optimise_strip=yes" >> env.custom
      printf '%s\n' "qbt_build_debug=no" >> env.custom
      printf '%s\n' "qbt_standard=20" >> env.custom
      printf '%s\n' "qbt_static_ish=no" >> env.custom
      printf '%s\n' "qbt_optimise=no" >> env.custom
  - runs: |
      export $(cat env.custom)
      /usr/bin/env bash ./qbt-nox-static.bash
      /usr/bin/env bash ./qbt-nox-static.bash update install_test
      /usr/bin/env bash ./qbt-nox-static.bash update install_core
      /usr/bin/env bash ./qbt-nox-static.bash -bs-a
      /usr/bin/env bash ./qbt-nox-static.bash zlib
      /usr/bin/env bash ./qbt-nox-static.bash iconv
      /usr/bin/env bash ./qbt-nox-static.bash icu
      /usr/bin/env bash ./qbt-nox-static.bash openssl
      /usr/bin/env bash ./qbt-nox-static.bash boost
      /usr/bin/env bash ./qbt-nox-static.bash libtorrent
      /usr/bin/env bash ./qbt-nox-static.bash double_conversion
      /usr/bin/env bash ./qbt-nox-static.bash qtbase
      /usr/bin/env bash ./qbt-nox-static.bash qttools
      /usr/bin/env bash ./qbt-nox-static.bash qbittorrent
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      mv qbt-build/bin/qbittorrent-nox ${{targets.destdir}}/usr/bin/qbittorrent-nox
      chmod 755 ${{targets.destdir}}/usr/bin/qbittorrent-nox
update:
  enabled: true
  github:
    identifier: userdocs/qbittorrent-nox-static
    strip-prefix: "release-"
  version-transform:
    - match: _v(\d)\.(\d)\.(\d+)$
      replace: .$1$2$3
