package:
  name: qbit-download-hook
  version: "1.0.3"
  epoch: 0
  copyright:
    - license: MIT
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/d4rkfella/qbit-download-hook
      tag: v${{package.version}}
      expected-commit: e0da80b49767d20eaaabfa391447088b6fdb6f57
  - uses: go/build
    with:
      packages: main.go
      output: qbit-download-hook
      ldflags: -X 'main.version=${{package.version}}'
update:
  enabled: true
  github:
    identifier: d4rkfella/qbit-download-hook
    strip-prefix: v
