package:
  name: smartctl_exporter
  description: Export smartctl statistics to prometheus
  version: 0.14.0
  epoch: 4
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - smartmontools
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-community/smartctl_exporter
      tag: v${{package.version}}
      expected-commit: ef5c03de02cb793e6a1540bef943fe6a167de635
  - uses: go/bump
    with:
      deps: |-
        golang.org/x/crypto@v0.48.0
        golang.org/x/net@v0.50.0
        golang.org/x/oauth2@v0.35.0
  - uses: go/build
    with:
      packages: .
      output: smartctl_exporter
      ldflags: -X 'github.com/prometheus/common/version.Version=${{package.version}}' -X 'github.com/prometheus/common/version.Revision=$(git rev-parse HEAD)' -X 'github.com/prometheus/common/version.Branch=$(git rev-parse --abbrev-ref HEAD)' -X 'github.com/prometheus/common/version.BuildUser=$(whoami)@$(hostname)' -X 'github.com/prometheus/common/version.BuildDate=$(git log -1 --format=%cd --date=format:'%Y%m%d-%H:%M:%S')'
  - uses: strip
update:
  enabled: true
  github:
    identifier: prometheus-community/smartctl_exporter
    strip-prefix: v
