package:
  name: radarr
  version: "6.4.1.10545"
  epoch: 0
  description: Movie download automation for usenet and torrents.
  copyright:
    - license: GPL-3.0-only
  dependencies:
    runtime:
      - icu
      - sqlite-libs
      - libssl3
      - zlib
environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - bash
      - curl
      - icu
pipeline:
  - uses: git-checkout
    with:
      expected-commit: 15369ed5c359c9704783d243ce2b55e59a40a3a3
      repository: https://github.com/Radarr/Radarr
      tag: v${{package.version}}
  - name: Install dependancies
    runs: |
      curl -sSL https://get.volta.sh | bash
      curl -sSL https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh | bash -s -- --jsonfile global.json
  - name: Build
    runs: "if [[ \"${{build.arch}}\" == \"aarch64\" ]]; then\n  runtime_arch=\"arm64\"\nelif [[ \"${{build.arch}}\" == \"x86_64\" ]]; then\n  runtime_arch=\"x64\"\nfi\n\nPATH=\"$HOME/.volta/bin:$HOME/.dotnet:$PATH\"      \n\nexport BROWSERSLIST_IGNORE_OLD_DATA=true\n\nyarn install --frozen-lockfile --network-timeout 120000\n\n_dotnet_arch=\"$runtime_arch\"\n_runtime=\"linux-$_dotnet_arch\"\n_framework=$(sed -n 's:.*<TargetFrameworks>\\([^<;]*\\).*:\\1:p' src/NzbDrone.Host/Radarr.Host.csproj | head -n1)\n_output=\"_output\"\n_destdir=\"${{targets.destdir}}/usr/lib/radarr\"\n_artifacts=\"$_output/$_framework/$_runtime/publish\"\n\nulimit -n 4096\ndotnet msbuild -restore src/Radarr.sln \\\n  -p:Configuration=Release \\\n  -p:Platform=Posix \\\n  -p:RuntimeIdentifiers=\"$_runtime\" \\\n  -p:SelfContained=true \\\n  -p:AssemblyConfiguration=\"master\" \\\n  -p:AssemblyVersion=\"${{package.version}}\" \\\n  -p:DebugSymbols=false \\\n  -p:DebugType=none \\\n  -p:SentryCliExecutable= \\\n  -p:SentryUploadSymbols=false \\\n  -p:SentryIncludeSources=false \\\n  -p:EmbedAllSources=false \\\n  -t:PublishAllRids\n\nyarn run build --env production\n\nchmod +x \"$_artifacts/ffprobe\"\n\necho \"Preparing package\"\n\nmkdir -p \"$_destdir\" \"${{targets.destdir}}/usr/bin\"\n\nprintf \"UpdateMethod=docker\\nBranch=%s\\nPackageVersion=%s\\nPackageAuthor=[d4rkfella](https://github.com/d4rkfella)\\n\" \"develop\" \"${{package.version}}\" > \"$_destdir/package_info\"\n\nmv \"$_output/UI\" \"$_artifacts\"\nmv $_output/Radarr.Update/$_framework/$_runtime/publish $_artifacts/Radarr.Update\n\necho \"Adding Radarr.Mono to UpdatePackage\"\ncp $_artifacts/Radarr.Mono.* $_artifacts/Radarr.Update\ncp $_artifacts/Mono.Posix.NETStandard.* $_artifacts/Radarr.Update\ncp $_artifacts/libMonoPosixHelper.* $_artifacts/Radarr.Update\n\nfind \"$_artifacts\" \\( \\\n  -name \"ServiceUninstall.*\" -o \\\n  -name \"ServiceInstall.*\" -o \\\n  -name \"Radarr.Windows.*\" -o \\\n  -name \"libcoreclrtraceptprovider.so\" \\\n\\) -delete\n\nmv \"$_artifacts\" \"$_destdir/bin\"\nmv LICENSE \"$_destdir/bin\"\n\nln -s /usr/lib/radarr/bin/Radarr \"${{targets.destdir}}/usr/bin/Radarr\"\n"
  - uses: strip
test:
  environment:
    contents:
      packages:
        - curl
        - bash
        - jq
        - xmlstarlet
  pipeline:
    - name: Check for missing dependancies
      uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
    - name: Run test script
      runs: |
        EXPECTED_VERSION="${{package.version}}" ./test.sh
update:
  enabled: true
  enable-prerelease-tags: true
  github:
    identifier: Radarr/Radarr
    strip-prefix: v
