package:
  name: seerr
  version: "3.3.0"
  epoch: 0
  description: Open-source media request and discovery manager for Jellyfin, Plex, and Emby.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs-22
environment:
  environment:
    REPRODUCIBLE: false
  contents:
    packages:
      - wolfi-baselayout
      - nodejs-22
      - pnpm
      - patch
pipeline:
  - uses: git-checkout
    with:
      expected-commit: 703faf95f454ffecae99a5e86ea761b3b524c6df
      repository: https://github.com/seerr-team/seerr
      tag: v${{package.version}}
      destination: seerr
  - name: Build
    working-directory: /home/build/seerr
    runs: |
      export NEXT_TELEMETRY_DISABLED=1
      export CYPRESS_INSTALL_BINARY=0
      export COMMIT_TAG=$(git rev-parse HEAD)
      pnpm install --frozen-lockfile
      pnpm build
      pnpm prune --prod --ignore-scripts
  - name: Delete linux-musl node-modules
    working-directory: /home/build/seerr
    runs: |
      find node_modules -name "*musl*" | xargs rm -rf
  - name: Prepare package
    working-directory: /home/build/seerr
    runs: |
      mkdir -p "${{targets.destdir}}/usr/lib/seerr"
      rm -rf .next/cache
      echo "{\"commitTag\": \"$(git rev-parse HEAD)\"}" > committag.json
      cp -af seerr-api.yml next.config.ts package.json committag.json .next public dist node_modules "${{targets.destdir}}/usr/lib/seerr"
test:
  environment:
    contents:
      packages:
        - curl
        - bash
        - jq
  pipeline:
    - name: Run test script
      runs: |
        EXPECTED_VERSION="${{package.version}}" ./test.sh
    - name: Check for missing dependancies
      uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
update:
  enabled: true
  github:
    identifier: seerr-team/seerr
    strip-prefix: v
