package:
  name: seerr
  version: "3.4.1"
  epoch: 2
  description: Open-source media request and discovery manager for Jellyfin, Plex, and Emby.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs-22
environment:
  environment:
    REPRODUCIBLE: false
  contents:
    packages:
      - wolfi-baselayout
      - nodejs-22
      - pnpm
      - patch
pipeline:
  - uses: git-checkout
    with:
      expected-commit: 69f73a6f1486fdb51b8ddae9a94a8dfb629f461c
      repository: https://github.com/seerr-team/seerr
      tag: v${{package.version}}
      destination: seerr
  - name: Build
    working-directory: /home/build/seerr
    runs: |
      export NEXT_TELEMETRY_DISABLED=1
      export CYPRESS_INSTALL_BINARY=0
      export COMMIT_TAG=$(git rev-parse HEAD)
      pnpm install --frozen-lockfile
      pnpm build
      pnpm prune --prod --ignore-scripts
  - name: Remove unused node module assets
    working-directory: /home/build/seerr
    runs: |
      if [ -d node_modules/.pnpm ]; then
        find node_modules/.pnpm -type d \( \
          -path "*ace-builds/src-noconflict" -o \
          -path "*ace-builds/src" -o \
          -path "*ace-builds/src-min" -o \
          -path "*country-flag-icons/react" -o \
          -path "*country-flag-icons/string" -o \
          -path "*country-flag-icons/1x1" -o \
          -path "*@heroicons/react/16" \
        \) -exec rm -rf {} + || true
      fi
      find node_modules -name "*musl*" | xargs rm -rf
  - name: Prepare package
    working-directory: /home/build/seerr
    runs: |
      mkdir -p "${{targets.destdir}}/usr/lib/seerr"
      rm -rf .next/cache
      echo "{\"commitTag\": \"$(git rev-parse HEAD)\"}" > committag.json
      cp -af seerr-api.yml next.config.ts package.json committag.json .next public dist node_modules "${{targets.destdir}}/usr/lib/seerr"
test:
  environment:
    contents:
      packages:
        - curl
        - bash
        - jq
  pipeline:
    - name: Run test script
      runs: |
        EXPECTED_VERSION="${{package.version}}" ./test.sh
    - name: Check for missing dependancies
      uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
update:
  enabled: true
  github:
    identifier: seerr-team/seerr
    strip-prefix: v
