package:
  name: pgadmin4
  version: 9.13
  epoch: 9
  description: pgAdmin 4 - PostgreSQL Tools for the Web
  copyright:
    - license: PostgreSQL
  dependencies:
    runtime:
      - py${{vars.py-version}}-bcrypt
      - py${{vars.py-version}}-cryptography
      - py${{vars.py-version}}-ldap3
      - py${{vars.py-version}}-psutil
      - postgresql-18-pgadmin-compat
vars:
  py-version: "3.13"
var-transforms:
  - from: ${{package.version}}
    match: '\.'
    replace: "_"
    to: mangled-package-version
environment:
  environment:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    REPRODUCIBLE: false
  contents:
    packages:
      - build-base
      - python-${{vars.py-version}}-dev
      - py${{vars.py-version}}-pip
      - py${{vars.py-version}}-bcrypt
      - py${{vars.py-version}}-cryptography
      - py${{vars.py-version}}-ldap3
      - py${{vars.py-version}}-psutil
      - postgresql-18-dev
      - nodejs
      - corepack
      - krb5-dev
      - bash
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pgadmin-org/pgadmin4
      tag: REL-${{vars.mangled-package-version}}
      expected-commit: "5b231ddd3f7aca5d6e7c03c21e7e1bc94b8c3b03"
  - name: build-venv
    runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/pgadmin4
      python${{vars.py-version}} -m venv --system-site-packages --without-pip --copies ${{targets.destdir}}/usr/lib/pgadmin4/venv
      ${{targets.destdir}}/usr/lib/pgadmin4/venv/bin/python3 -m pip install --no-cache-dir -r requirements.txt
      ${{targets.destdir}}/usr/lib/pgadmin4/venv/bin/python3 -m pip install --no-cache-dir gunicorn==25.3.0
  - name: build-docs
    runs: |
      pip install --no-cache-dir sphinx sphinxcontrib-youtube
      sphinx-build docs/en_US docs/en_US/_build/html
      rm -rf docs/en_US/_build/html/.doctrees
      rm -rf docs/en_US/_build/html/_sources
      rm -rf docs/en_US/_build/html/_static/*.png
  - name: patch-webpack-config
    runs: |
      sed -i "s/filename: 'fonts\/\[name\]\.\[ext\]'/filename: 'fonts\/[base]'/" web/webpack.config.js
  - name: build-js
    runs: |
      cd web
      export CPPFLAGS="-DPNG_ARM_NEON_OPT=0"
      corepack enable
      yarn set version berry
      yarn set version 4
      yarn install
      yarn run bundle
      rm -rf node_modules pgadmin/static/js/generated/.cache yarn.lock package.json .[^.]* babel.cfg webpack.* jest.config.js babel.*
  - name: prepare package
    runs: |
      mkdir -p "${{targets.destdir}}/usr/lib/pgadmin4/docs"
      cp -r web/. "${{targets.destdir}}/usr/lib/pgadmin4/"
      cp -r docs/en_US/_build/html/. "${{targets.destdir}}/usr/lib/pgadmin4/docs/"
      cp pkg/docker/run_pgadmin.py "${{targets.destdir}}/usr/lib/pgadmin4/"
      cp LICENSE "${{targets.destdir}}/usr/lib/pgadmin4/LICENSE"
      find "${{targets.destdir}}" -type d -name '__pycache__' -exec rm -rf {} + || true
update:
  enabled: true
  version-transform:
    - match: _(\d+)$
      replace: .${1}
  github:
    identifier: pgadmin-org/pgadmin4
    strip-prefix: REL-
    tag-filter-prefix: REL-
    use-tag: true
test:
  pipeline:
    - name: Check for missing dependancies
      uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
