package:
  name: unrar
  version: "7.3.1"
  epoch: 1
  description: UnRAR - free utility for RAR archives
  copyright:
    - license: UnRAR
      license-path: license.txt
environment:
  contents:
    packages:
      - wolfi-baselayout
      - build-base
pipeline:
  - uses: fetch
    with:
      uri: https://www.rarlab.com/rar/unrarsrc-${{package.version}}.tar.gz
      expected-sha256: 634900842a3737d9cc15bbcc71d4c74cc713437e0bca296a573424fe5f2660ab
  - uses: autoconf/make
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      mkdir -p ${{targets.destdir}}/usr/share/licenses/unrar
      install -v -m755 unrar ${{targets.destdir}}/usr/bin
      install -v -m644 license.txt ${{targets.destdir}}/usr/share/licenses/unrar/LICENSE
  - uses: strip
test:
  pipeline:
    - uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
update:
  enabled: true
  release-monitor:
    identifier: 13306
