package:
  name: unrar
  version: "7.2.5"
  epoch: 0
  description: UnRAR - free utility for RAR archives
environment:
  contents:
    packages:
      - wolfi-baselayout
      - build-base
pipeline:
  - uses: fetch
    with:
      uri: https://www.rarlab.com/rar/unrarsrc-${{package.version}}.tar.gz
      expected-sha256: 3d7b402ce7b9825af32a5f593379269e742c883d9d276527be19d0e9f6a114f9
  - uses: autoconf/make
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      install -v -m755 unrar ${{targets.destdir}}/usr/bin
  - uses: strip
test:
  pipeline:
    - uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
update:
  enabled: true
  release-monitor:
    identifier: 13306
