package:
  name: prowlarr
  version: "2.6.1.5509"
  epoch: 0
  description: Prowlarr is an indexer manager/proxy built on the popular *arr .net/reactjs base stack to integrate with your various PVR apps. Prowlarr supports management of both Torrent Trackers and Usenet Indexers. It integrates seamlessly with Lidarr, Mylar3, Radarr, Readarr, and Sonarr offering complete management of your indexers with no per app Indexer setup required (we do it all).
  copyright:
    - license: GPL-3.0-only
  dependencies:
    runtime:
      - icu
      - sqlite-libs
      - libssl3
      - zlib
environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - bash
      - curl
      - icu
pipeline:
  - uses: git-checkout
    with:
      expected-commit: c6034c86f0d6b5e7a04b7dd944c9e1067808b026
      repository: https://github.com/Prowlarr/Prowlarr
      tag: v${{package.version}}
  - name: Install dependancies
    runs: |
      curl -sSL https://get.volta.sh | bash
      curl -sSL https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh | bash -s -- --jsonfile global.json
  - name: Build
    runs: |
      if [[ "${{build.arch}}" == "aarch64" ]]; then
        runtime_arch="arm64"
      elif [[ "${{build.arch}}" == "x86_64" ]]; then
        runtime_arch="x64"
      fi

      PATH="$HOME/.volta/bin:$HOME/.dotnet:$PATH"

      export BROWSERSLIST_IGNORE_OLD_DATA=true

      volta install node@20
      volta install yarn@1.22

      yarn install --frozen-lockfile --network-timeout 120000

      _dotnet_arch="$runtime_arch"
      _runtime="linux-$_dotnet_arch"
      _framework=$(sed -n 's:.*<TargetFrameworks>\([^<;]*\).*:\1:p' src/NzbDrone.Host/Prowlarr.Host.csproj | head -n1)
      _output="_output"
      _destdir="${{targets.destdir}}/usr/lib/prowlarr"
      _artifacts="$_output/$_framework/$_runtime/publish"

      ulimit -n 4096

      dotnet msbuild -restore src/Prowlarr.sln \
        -p:Configuration=Release \
        -p:Platform=Posix \
        -p:RuntimeIdentifiers="$_runtime" \
        -p:AssemblyConfiguration="master" \
        -p:AssemblyVersion="${{package.version}}" \
        -p:DebugSymbols=false \
        -p:DebugType=none \
        -p:SentryCliExecutable= \
        -p:SentryUploadSymbols=false \
        -p:SentryIncludeSources=false \
        -p:EmbedAllSources=false \
        -t:PublishAllRids

      yarn run build --env production

      echo "Preparing package"

      mkdir -p "$_destdir" "${{targets.destdir}}/usr/bin"

      printf "UpdateMethod=docker\nBranch=%s\nPackageVersion=%s\nPackageAuthor=[d4rkfella](https://github.com/d4rkfella)\n" "develop" "${{package.version}}" > "$_destdir/package_info"

      cp -r "$_output/UI" "$_artifacts"
      cp -r $_output/Prowlarr.Update/$_framework/$_runtime/publish $_artifacts/Prowlarr.Update

      echo "Adding Prowlarr.Mono to UpdatePackage"
      cp $_artifacts/Prowlarr.Mono.* $_artifacts/Prowlarr.Update
      cp $_artifacts/Mono.Posix.NETStandard.* $_artifacts/Prowlarr.Update
      cp $_artifacts/libMonoPosixHelper.* $_artifacts/Prowlarr.Update

      find "$_artifacts" \( \
        -name "ServiceUninstall.*" -o \
        -name "ServiceInstall.*" -o \
        -name "Prowlarr.Windows.*" -o \
        -name "libcoreclrtraceptprovider.so" -o \
        -name "libmsalruntime.so" \
      \) -delete

      cp -af "$_artifacts" "$_destdir/bin"

      ln -s /usr/lib/prowlarr/bin/Prowlarr "${{targets.destdir}}/usr/bin/Prowlarr"
test:
  environment:
    contents:
      packages:
        - curl
        - bash
        - jq
        - xmlstarlet
  pipeline:
    - name: Check for missing dependancies
      uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
    - name: Run test script
      runs: |
        EXPECTED_VERSION="${{package.version}}" ./test.sh
update:
  enabled: true
  enable-prerelease-tags: true
  github:
    identifier: Prowlarr/Prowlarr
    strip-prefix: v
