package:
  name: vaultwarden
  version: "1.35.6"
  epoch: 0
  description: "Unofficial Bitwarden compatible server written in Rust (glibc)"
  copyright:
    - license: GPL-3.0-or-later
  dependencies:
    runtime:
      - wolfi-base
      - ca-certificates
      - openssl
      - libpq-18
      - curl
environment:
  environment:
    FEATURES: "postgresql"
    REPRODUCIBLE: false
  contents:
    packages:
      - wolfi-base
      - cargo-auditable
      - pkgconf
      - clang
      - rust
      - curl
      - openssl-dev
      - postgresql-dev
      - zlib-dev
      - bash
      - build-base
      - nodejs-22
      - npm
      - python-3.14
      - yq
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dani-garcia/vaultwarden
      tag: ${{package.version}}
      expected-commit: bb549986e636ea3ee54ae7bc59bf267d0ec61dc8
      destination: vaultwarden
  - name: build-vaultwarden
    working-directory: /home/build/vaultwarden
    runs: |
      cargo auditable build \
        --features ${FEATURES} \
        --release \
        --target ${{build.arch}}-unknown-linux-gnu \
        --bin vaultwarden
  - uses: git-checkout
    with:
      repository: https://github.com/dani-garcia/bw_web_builds
      destination: bw_web_builds
  - name: build-web-vault
    working-directory: /home/build/bw_web_builds
    runs: |
      set -eux
      git fetch --tags
      BW_WEB_BUILDS_VERSION=$(yq '.vault_version' /home/build/vaultwarden/docker/DockerSettings.yaml | tr -d '"')
      git checkout "${BW_WEB_BUILDS_VERSION}"
      export VAULT_VERSION=$(grep '^ARG VAULT_VERSION=' Dockerfile | cut -d'=' -f2)
      echo ${VAULT_VERSION}
      make checkout
      cd web-vault
      WEB_VAULT_TAG=$(git describe --tags --exact-match 2>/dev/null || git describe --tags 2>/dev/null || echo "${VAULT_VERSION}")
      echo "WEB_VAULT_TAG: ${WEB_VAULT_TAG}"
      npm ci
      cd apps/web
      npm run dist:oss:selfhost
      cd build
      printf '{"version":"%s"}\n' "${WEB_VAULT_TAG}" > vw-version.json
  - name: prepare-package
    runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      mkdir -p ${{targets.destdir}}/usr/lib/vw_web_vault
      cp /home/build/vaultwarden/target/${{build.arch}}-unknown-linux-gnu/release/vaultwarden ${{targets.destdir}}/usr/bin/vaultwarden
      install -m555 -D start.sh ${{targets.destdir}}/usr/bin/start.sh
      cp -r /home/build/bw_web_builds/web-vault/apps/web/build/* ${{targets.destdir}}/usr/lib/vw_web_vault
update:
  enabled: true
  github:
    identifier: dani-garcia/vaultwarden
    strip-prefix: v
