package:
  name: qbit-init
  version: "0.3.0"
  epoch: 2
  copyright:
    - license: MIT
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/d4rkfella/qbit-init
      tag: v${{package.version}}
      expected-commit: 77b9bc6bd667039f8b5b06baf01c5e58af7bbb80
  - uses: go/build
    with:
      packages: main.go
      output: qbit-init
update:
  enabled: true
  github:
    identifier: d4rkfella/qbit-init
    strip-prefix: v
