package:
  name: opnsense-exporter
  version: "0.0.13"
  epoch: 0
  description: OPNsense Exporter for Prometheus
  copyright:
    - license: Apache-2.0
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/AthennaMind/opnsense-exporter
      tag: v${{package.version}}
      expected-commit: 8fa4604f33d75ef1adf832045088dbbaa725d92d
  - uses: go/build
    with:
      packages: main.go
      output: opnsense-exporter
      ldflags: -X 'main.version=${{package.version}}'
update:
  enabled: true
  github:
    identifier: AthennaMind/opnsense-exporter
    strip-prefix: v
