package:
  name: qbit_manage
  version: "4.6.5"
  epoch: 2
  description: This tool will help manage tedious tasks in qBittorrent and automate them. Tag, categorize, remove Orphaned data, remove unregistered torrents and much much more.
  copyright:
    - license: MIT
environment:
  environment:
    REPRODUCIBLE: false
  contents:
    packages:
      - python-3.13
      - py3.13-pip
      - py3.13-virtualenv-bin
pipeline:
  - uses: git-checkout
    with:
      expected-commit: 371627bbeb082e68f057bbe4599565c2e63a14c7
      repository: https://github.com/StuffAnThings/qbit_manage
      tag: v${{package.version}}
  - name: Prepare package
    runs: |
      APPDIR="${{targets.destdir}}/usr/lib/qbitmanage/app"
      mkdir -p "${APPDIR}"
      cp /home/build/pyproject.toml /home/build/VERSION /home/build/setup.py "${APPDIR}/"
      virtualenv --copies "${APPDIR}/venv"
      sh -c "source '${APPDIR}/venv/bin/activate' && pip install --upgrade --no-cache-dir ."
      cp -af /home/build/modules \
             /home/build/qbit_manage.py \
             /home/build/VERSION \
             /home/build/LICENSE \
             /home/build/scripts \
             /home/build/docs \
             /home/build/icons \
             /home/build/web-ui \
             "${APPDIR}/"
test:
  pipeline:
    - name: Check for missing dependancies
      uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
update:
  enabled: true
  github:
    identifier: StuffAnThings/qbit_manage
    strip-prefix: v
