package:
  name: autobrr
  version: "1.77.1"
  epoch: 0
  description: "Autobrr download automation tool"
  copyright:
    - license: GPL-2.0-or-later
environment:
  contents:
    packages:
      - nodejs-22
      - pnpm
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/autobrr/autobrr
      tag: v${{package.version}}
      expected-commit: 1f584b262ab5543cdd0da6cdec320f27f30d7b00
  - working-directory: /home/build/web
    runs: |
      pnpm install --frozen-lockfile
      pnpm run build
  - uses: go/build
    with:
      packages: cmd/autobrr/main.go
      output: autobrr
      ldflags: -X 'main.version=${{package.version}}' -X 'main.commit=$(git rev-parse HEAD)' -X 'main.date=$(git show -s --date=format:%Y-%m-%dT%H:%M:%SZ --format=%cd HEAD)'
  - uses: go/build
    with:
      packages: cmd/autobrrctl/main.go
      output: autobrrctl
      ldflags: -X 'main.version=${{package.version}}' -X 'main.commit=$(git rev-parse HEAD)' -X 'main.date=$(git show -s --date=format:%Y-%m-%dT%H:%M:%SZ --format=%cd HEAD)'
  - uses: strip
update:
  enabled: true
  github:
    identifier: autobrr/autobrr
    strip-prefix: v
