package:
  name: sonarr
  version: 4.0.16.2944
  epoch: 2
  description: Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available.
  copyright:
    - license: GPL-3.0-only
environment:
  environment:
    PATH: "$HOME/.volta/bin:$HOME/.dotnet:$PATH"
    BROWSERSLIST_IGNORE_OLD_DATA: true
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - bash
      - curl
      - icu
pipeline:
  - uses: git-checkout
    with:
      expected-commit: 52972e7efcce800560cbbaa64f5f76aaef6cbe77
      repository: https://github.com/Sonarr/Sonarr
      tag: v${{package.version}}
  - name: Install dependancies
    runs: |
      curl -sSL https://get.volta.sh | bash
      curl -sSL https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh | bash -s -- --jsonfile global.json
  - name: Build
    runs: |
      PATH="$HOME/.volta/bin:$HOME/.dotnet:$PATH"
      
      if [[ "${{build.arch}}" == "aarch64" ]]; then
        runtime_arch="arm64"
      elif [[ "${{build.arch}}" == "x86_64" ]]; then
        runtime_arch="x64"
      fi

      yarn install --frozen-lockfile --network-timeout 120000

      _dotnet_arch="$runtime_arch"
      _runtime="linux-$_dotnet_arch"
      _framework="net6.0"
      _output="_output"
      _destdir="${{targets.destdir}}/usr/lib/sonarr"
      _artifacts="$_output/$_framework/$_runtime/publish"

      ulimit -n 4096

      dotnet publish src \
        -p:AssemblyConfiguration="main" \
        -p:AssemblyVersion="${{package.version}}" \
        -p:RuntimeIdentifier="$_runtime" \
        -p:Configuration=Release \
        -p:DebugSymbols=false \
        -p:DebugType=none \
        -p:SelfContained=true \
        -p:SentryCliExecutable= \
        -p:SentryUploadSymbols=false \
        -p:SentryIncludeSources=false \
        -p:EmbedAllSources=false \
        -f "$_framework"

      yarn build --env production --no-stats

      chmod +x "$_artifacts"/ffprobe

      find "$_artifacts" \( \
        -name "ServiceUninstall.*" -o \
        -name "ServiceInstall.*" -o \
        -name "Sonarr.Windows.*" \
      \) -delete

      mv "$_output"/UI "$_artifacts"

      echo "Preparing package"

      mkdir -p "$_destdir" "${{targets.destdir}}/usr/bin"
      printf "UpdateMethod=docker\nBranch=%s\nPackageVersion=%s\nPackageAuthor=[d4rkfella](https://github.com/d4rkfella)\n" "develop" "${{package.version}}" > "$_destdir"/package_info

      cp -af "$_artifacts" "$_destdir"/bin

      ln -s /usr/lib/sonarr/bin/Sonarr "${{targets.destdir}}"/usr/bin/Sonarr
  - uses: strip
test:
  environment:
    contents:
      packages:
        - curl
        - bash
        - jq
        - xmlstarlet
        - lttng-ust
  pipeline:
    - runs: ln -s /usr/lib/liblttng-ust.so.1 /usr/lib/liblttng-ust.so.0
    - name: Check for missing dependancies
      uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
    - name: Run test script
      runs: |
        EXPECTED_VERSION="${{package.version}}" ./test.sh
update:
  enabled: true
  github:
    identifier: Sonarr/Sonarr
    strip-prefix: v
