package:
  name: sonarr
  version: "4.0.19.3006"
  epoch: 0
  description: Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available.
  copyright:
    - license: GPL-3.0-only
  dependencies:
    runtime:
      - icu
      - sqlite-libs
      - libssl3
      - zlib
environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - bash
      - curl
      - icu
pipeline:
  - uses: git-checkout
    with:
      expected-commit: 288f73ce9005128b3060a4629d605e693ce9fa57
      repository: https://github.com/Sonarr/Sonarr
      tag: v${{package.version}}
  - name: Install dependancies
    runs: |
      curl -sSL https://get.volta.sh | bash
      curl -sSL https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh | bash -s -- --jsonfile global.json
  - name: Build
    runs: |
      if [[ "${{build.arch}}" == "aarch64" ]]; then
        runtime_arch="arm64"
      elif [[ "${{build.arch}}" == "x86_64" ]]; then
        runtime_arch="x64"
      fi

      PATH="$HOME/.volta/bin:$HOME/.dotnet:$PATH"

      export BROWSERSLIST_IGNORE_OLD_DATA=true

      yarn install --frozen-lockfile --network-timeout 120000

      _dotnet_arch="$runtime_arch"
      _runtime="linux-$_dotnet_arch"
      _framework=$(sed -n 's:.*<TargetFrameworks>\([^<;]*\).*:\1:p' src/NzbDrone.Host/Sonarr.Host.csproj | head -n1)
      _output="_output"
      _destdir="${{targets.destdir}}/usr/lib/sonarr"
      _artifacts="$_output/$_framework/$_runtime/publish"

      ulimit -n 4096
      dotnet msbuild -restore src/Sonarr.sln \
        -p:Configuration=Release \
        -p:Platform=Posix \
        -p:RuntimeIdentifiers="$_runtime" \
        -p:AssemblyConfiguration="main" \
        -p:AssemblyVersion="${{package.version}}" \
        -p:DebugSymbols=false \
        -p:DebugType=none \
        -p:SentryCliExecutable= \
        -p:SentryUploadSymbols=false \
        -p:SentryIncludeSources=false \
        -p:EmbedAllSources=false \
        -t:PublishAllRids

      yarn build --env production

      chmod +x "$_artifacts"/ffprobe

      echo "Preparing package"

      mkdir -p "$_destdir" "${{targets.destdir}}/usr/bin"

      printf "UpdateMethod=docker\nBranch=%s\nPackageVersion=%s\nPackageAuthor=[d4rkfella](https://github.com/d4rkfella)\n" "develop" "${{package.version}}" > "$_destdir"/package_info

      mv "$_output/UI" "$_artifacts"
      mv $_output/Sonarr.Update/$_framework/$_runtime/publish $_artifacts/Sonarr.Update

      echo "Adding Sonarr.Mono to UpdatePackage"
      cp $_artifacts/Sonarr.Mono.* $_artifacts/Sonarr.Update
      cp $_artifacts/Mono.Posix.NETStandard.* $_artifacts/Sonarr.Update
      cp $_artifacts/libMonoPosixHelper.* $_artifacts/Sonarr.Update

      find "$_artifacts" \( \
        -name "ServiceUninstall.*" -o \
        -name "ServiceInstall.*" -o \
        -name "Sonarr.Windows.*" -o \
        -name "libcoreclrtraceptprovider.so" \
      \) -delete

      mv "$_artifacts" "$_destdir/bin"
      mv LICENSE.md "$_destdir/bin"

      ln -s /usr/lib/sonarr/bin/Sonarr "${{targets.destdir}}"/usr/bin/Sonarr
  - uses: strip
test:
  environment:
    contents:
      packages:
        - curl
        - bash
        - jq
        - xmlstarlet
  pipeline:
    - name: Check for missing dependancies
      uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
    - name: Run test script
      runs: |
        EXPECTED_VERSION="${{package.version}}" ./test.sh
update:
  enabled: true
  enable-prerelease-tags: true
  github:
    identifier: Sonarr/Sonarr
    strip-prefix: v
