package:
  name: bazarr
  version: "1.5.5_beta14"
  epoch: 0
  description: Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements. You define your preferences by TV show or movie and Bazarr takes care of everything for you.
  copyright:
    - license: GPL-3.0-only
  dependencies:
    runtime:
      - unrar
      - ffmpeg
var-transforms:
  - from: "${{package.version}}"
    match: "_beta"
    replace: "-beta."
    to: mangled-package-version
environment:
  environment:
    PYTHONHASHSEED: 0
    PYTHONDONTWRITEBYTECODE: 1
  contents:
    packages:
      - python-3.13
      - py3.13-pip
      - py3.13-virtualenv-bin
      - nodejs
      - npm
pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8fd87e55f133c91e18ca915b66da46132a0ad8c7
      repository: https://github.com/morpheus65535/bazarr
      tag: v${{vars.mangled-package-version}}
  - uses: patch
    with:
      patches: GHSA-h95x-26f3-88hr.patch
  - name: Build frontend
    working-directory: /home/build/frontend
    runs: |
      npx update-browserslist-db@latest
      npm install
      npm run build
  - name: Update vendored dependencies
    runs: |
      set -euo pipefail

      DEST_DIR="/tmp"
      LIBS_DIR="libs"

      echo "Updating vendored dependencies..."
      for entry in \
        "waitress-3.0.0.dist-info waitress==3.0.2" \
        "jinja2-3.1.5.dist-info jinja2==3.1.6" \
        "h11-0.14.0.dist-info h11==0.16.0" \
        "urllib3-2.2.3.dist-info urllib3==2.6.3" \
        "Flask_Cors-5.0.0.dist-info flask_cors==6.0.2" \
        "requests-2.32.3.dist-info requests==2.32.5"
      do
          OLD_DIST=$(printf '%s' "$entry" | cut -d' ' -f1)
          NEW_SPEC=$(printf '%s' "$entry" | cut -d' ' -f2)

          PACKAGE_NAME=$(printf '%s' "$NEW_SPEC" | cut -d= -f1)
          VERSION=$(printf '%s' "$NEW_SPEC" | cut -d= -f3)

          if [ -d "$LIBS_DIR/$OLD_DIST" ]; then
              echo "Updating $PACKAGE_NAME to version $VERSION..."
              rm -rf "$LIBS_DIR/$OLD_DIST"
              pip download --no-deps --dest="$DEST_DIR" "$NEW_SPEC"
              python3 -m zipfile -e "$DEST_DIR/${PACKAGE_NAME}-${VERSION}-py3-none-any.whl" "$LIBS_DIR/"
          else
              echo "Warning: $LIBS_DIR/$OLD_DIST not found, skipping"
          fi
      done
  - name: Fix SSL verification
    runs: |
      set -euo pipefail

      if ! head -n 15 "libs/urllib3/connectionpool.py" | grep -q "import ssl"; then
        sed -i '/from __future__ import annotations/a import ssl' "libs/urllib3/connectionpool.py"
        echo "'ssl package import' has been added to the top of the file."
      else
        echo "'ssl package is already imported."
      fi

      sed -i 's/cert_reqs=self\.cert_reqs/cert_reqs=ssl.CERT_REQUIRED/' "libs/urllib3/connectionpool.py"
  - name: Prepare package
    runs: |
      set -euo pipefail

      APPDIR="${{targets.destdir}}/usr/lib/bazarr/app"
      FILE_LIST="$(cat .github/files_to_copy)"

      mkdir -p "${APPDIR}"
      virtualenv --copies "${APPDIR}/venv"
      sed -i '/lxml/ s/lxml>=4.3.0, <5.0.0/lxml>=5.0.0/' requirements.txt
      sh -c "source '${APPDIR}/venv/bin/activate' && pip install --upgrade --no-cache-dir -r requirements.txt -r postgres-requirements.txt"

      git describe --abbrev=0 > VERSION

      while IFS= read -r f
      do
          echo "**** copying $f to release ****"
          cp -r --parents "$f" "$APPDIR"
      done < .github/files_to_copy

      cp VERSION "${APPDIR}"

      printf "UpdateMethod=docker\nBranch=development\nPackageVersion=${{package.version}}\nPackageAuthor=d4rkfella" > ${{targets.destdir}}/usr/lib/bazarr/package_info
test:
  environment:
    contents:
      packages:
        - curl
        - bash
        - jq
        - yq
  pipeline:
    - name: Check for missing dependancies
      uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
    - name: Run test script
      runs: |
        EXPECTED_VERSION="${{vars.mangled-package-version}}" test/test.sh
update:
  enabled: true
  enable-prerelease-tags: true
  version-transform:
    - match: "-beta."
      replace: "_beta"
  github:
    identifier: morpheus65535/bazarr
    strip-prefix: v
