package:
  name: bazarr
  version: "1.6.2_beta2"
  epoch: 0
  description: Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements. You define your preferences by TV show or movie and Bazarr takes care of everything for you.
  copyright:
    - license: GPL-3.0
  dependencies:
    runtime:
      - unrar
      - ffmpeg
var-transforms:
  - from: "${{package.version}}"
    match: "_beta"
    replace: "-beta."
    to: mangled-package-version
environment:
  environment:
    PYTHONHASHSEED: 0
    PYTHONDONTWRITEBYTECODE: 1
    HUSKY: 0
  contents:
    packages:
      - python-3.13
      - py3.13-pip
      - nodejs
      - npm
      - node-gyp
pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2a9f0b3d1d51a5979b68d3ae018aafa1c6739332
      repository: https://github.com/morpheus65535/bazarr
      tag: v${{vars.mangled-package-version}}
  - uses: patch
    with:
      patches: GHSA-h95x-26f3-88hr.patch
  - name: Build frontend
    working-directory: /home/build/frontend
    runs: |
      npm ci --no-audit --no-fund
      npm run build
  - name: Prepare package
    runs: |
      set -euo pipefail

      APPDIR="${{targets.destdir}}/usr/lib/bazarr/app"

      mkdir -p "${APPDIR}"

      python3 -m venv --without-pip --copies "${APPDIR}/venv"

      pip install --upgrade --no-cache-dir --prefix "${APPDIR}/venv" -r requirements.txt -r postgres-requirements.txt

      git describe --abbrev=0 > VERSION && install -m444 VERSION "${APPDIR}"

      while IFS= read -r f
      do
          echo "**** copying $f to bazarr app directory ****"
          cp -r --parents "$f" "$APPDIR"
      done < .github/files_to_copy

      install -Dm444 LICENSE "${{targets.destdir}}/usr/share/licenses/bazarr/LICENSE"

      printf "UpdateMethod=docker\nBranch=development\nPackageVersion=${{package.version}}\nPackageAuthor=d4rkfella" > ${{targets.destdir}}/usr/lib/bazarr/package_info
test:
  environment:
    contents:
      packages:
        - curl
        - bash
        - jq
        - yq
  pipeline:
    - name: Check for missing dependancies
      uses: test/tw/ldd-check
      with:
        packages: ${{package.name}}
    - name: Run test script
      runs: |
        EXPECTED_VERSION="${{vars.mangled-package-version}}" test/test.sh
update:
  enabled: true
  enable-prerelease-tags: true
  version-transform:
    - match: "-beta."
      replace: "_beta"
  github:
    identifier: morpheus65535/bazarr
    strip-prefix: v
