name: Melange Build

on: 
  push:
    branches: ["main"]
    paths: ["src/packages/**/melange.yaml"]
  workflow_dispatch:
    inputs:
      package:
        description: "Package folder name (e.g. nginx, vaultwarden, etc)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  setup-build-matrix:
    runs-on: ubuntu-24.04
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Get Changed Files
        if: ${{ github.event_name == 'push' }}
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # 47.0.6
        with:
          files: src/packages/**/melange.yaml
          matrix: true

      - name: Set packages matrix output
        id: set-packages
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "packages=[\"src/packages/${{ github.event.inputs.package }}/melange.yaml\"]" >> "$GITHUB_OUTPUT"
          else
            FILES='${{ steps.changed-files.outputs.all_changed_files }}'
            if [ -z "$FILES" ]; then
              echo "packages=[]" >> "$GITHUB_OUTPUT"
            else
              echo "packages=$FILES" >> "$GITHUB_OUTPUT"
            fi
          fi

  setup-build-enviroment:
    needs: setup-build-matrix
    if: ${{ needs.setup-build-matrix.outputs.packages != '[]' }}
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      max-parallel: 2
    uses: ./.github/workflows/melange-build-setup.yaml
    with:
      arch: ${{ matrix.arch }}

  build:
    needs: [setup-build-matrix,setup-build-enviroment]
    if: ${{ needs.setup-build-matrix.outputs.packages != '[]' }}
    strategy:
      matrix:
        packages: ${{ fromJSON(needs.setup-build-matrix.outputs.packages) }}
        arch: [x86_64, aarch64]
      max-parallel: 4
      fail-fast: false
    runs-on: ${{ matrix.arch == 'x86_64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit
      
      - name: Set Cache Key
        id: cache
        run: echo "key=$(date -u +'%G-%V')" >> $GITHUB_OUTPUT

      - name: Restore cached build tools
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: build-dependencies-${{ matrix.arch }}-${{ steps.cache.outputs.key }}
          fail-on-cache-miss: true
          path: |
            /usr/local/bin/bwrap
            /usr/local/bin/melange
            /usr/local/bin/yq

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get pipelines from wolfi-dev/os
        run: |
          git clone --depth 1 --filter=blob:none --no-checkout https://github.com/wolfi-dev/os.git
          pushd os
          git sparse-checkout set --no-cone pipelines
          git checkout main
          mv pipelines $GITHUB_WORKSPACE/
          popd
          rm -rf os

      - name: Build and Push to Artifactory
        uses: d4rkfella/actions/melange-build@main
        with:
          arch: ${{ matrix.arch }}
          oidc-provider-name: github-oidc
          artifactory-url: https://packages.darkfellanetwork.com
          artifactory-repository-path: wolfi-os/latest/main
          config: ${{ matrix.packages }}
          sign-package: true
          signing-key: ${{ secrets.MELANGE_PRIVATE_KEY }}
          maintainer: darkfella
          pipeline-dir: ${{ github.workspace }}/pipelines
          repository-append: https://packages.darkfellanetwork.com/artifactory/wolfi-os/latest/main,https://packages.wolfi.dev/os
          keyring-append: https://packages.darkfellanetwork.com/artifactory/wolfi-os/melange.rsa.pub,https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
          tests-repository-append: https://packages.darkfellanetwork.com/artifactory/wolfi-os/latest/main,https://packages.wolfi.dev/os
          tests-keyring-append: https://packages.darkfellanetwork.com/artifactory/wolfi-os/melange.rsa.pub,https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
