name: Melange Renovator
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-packages:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      
      - name: Run renovator
        id: check-updates
        uses: docker://ghcr.io/d4rkfella/melange-renovator:v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -aws-endpoint=${{ secrets.AWS_ENDPOINT }}
            -aws-access-key=${{ secrets.AWS_ACCESS_KEY_ID }}
            -aws-secret-key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            -s3-bucket=melange-renovator
            -concurrency=10
